### ISSUE TITLE
`ModuleNotFoundError` thrown when importing libraries

### ISSUE THREAD

**Issue by ChantalMB** [conda-incubator/condacolab#19]
I installed `condacolab` then added my `environment.yml` as instructed in the README and everything installed perfectly, but when I went to run my code a `ModuleNotFoundError` was thrown at my import statement. I double-checked everything had installed correctly with `conda list` and the lib was definitely there, so I went to the [setup colab notebook](https://colab.research.google.com/drive/1c_RGCgQeLHVXlF44LyOFjfUW32CmG6BP) that's linked in the README and tried running the code found there and was met with the same issue:
<img width="1059" alt="Screen Shot 2021-12-05 at 10 08 03 PM" src="https://user-images.githubusercontent.com/56129893/144781927-83713126-6128-4240-b221-173ad024f5aa.png">

If I check the python and tensorflow version in my notebook, both return the correct versions installed via conda, so totally not sure why other packages aren't being recognized.

I'm not super technically-inclined so I unfortunately have no idea what the issue could be that's causing this-- it very well could be that I'm accidentally missing some sort of vital step! Otherwise, perhaps there was some sort of update that's causing things to install in the wrong place? Sorry I can't be of more help!

**Comment by jaimergp** [comment]
Ah, sorry, that example is a bit outdated. OpenMM changed their namespace so now you should do `from openmm.testInstallation import main`.

**Comment by ChantalMB** [comment]
Ha I can't believe I didn't catch the fact that I was literally installing `openmm` yet importing something else!

Looks like my importing issue is caused by something else then, I'll try playing with my `environment.yml` a bit more. Thanks for your quick response!
