### ISSUE TITLE
Entry points in installed conda packages are not found

### ISSUE THREAD

**Issue by jchodera** [conda-incubator/condacolab#20]
After `condacolab` is installed, entry points that are provided with subsequently installed conda packages are not found by [`pkg_resources.iter_entry_points()`](https://setuptools.pypa.io/en/latest/pkg_resources.html#convenience-api). Instead, it looks like only the original entry points provided with the default colab Python installation are found.

Here is a [simple notebook to reproduce the issue](https://colab.research.google.com/gist/jchodera/9ed861c2f991974c3155e42b6620545f/condacolab-entry-points-bug-reproduction.ipynb).

This is probably simple to fix, but I don't quite understand enough about entry point discovery to know how to do so.

**Comment by jaimergp** [comment]
Hi John, I think `pkg_resources` is [not the recommended way to query these things anymore.](https://importlib-metadata.readthedocs.io/en/latest/using.html) Use `importlib_metadata`. I checked on your example and it works:

```python
>>> from importlib_metadata import entry_points
>>> entry_points().select(group="openforcefield.smirnoff_forcefield_directory")
[EntryPoint(name='get_forcefield_dirs_paths', value='openforcefields.openforcefields:get_forcefield_dirs_paths', group='openforcefield.smirnoff_forcefield_directory')]

```

**Comment by jchodera** [comment]
Thanks, @jaimergp! I'll make sure that we update this throughout our ecosystem.

**Comment by jchodera** [comment]
Huzzah! Thanks!
