### ISSUE TITLE
pinning does not match what's currently installed

### ISSUE THREAD

**Issue by wfreinhart** [conda-incubator/condacolab#3]
When running the example notebook (as well as my own notebooks), I get a pinning error from `!mamba install -q openmm`:

> Your pinning does not match what's currently installed. Please remove the pin and fix your installation
>   Pin: python=3.7
>   Currently installed: conda-forge/linux-64::python==3.6.12=hffdb5ce_0_cpython

I suppose something may have changed with colab recently. I'm not familiar with mamba so perhaps there is an easy way to update this, but I don't know it. Thanks for your help!

**Comment by jaimergp** [comment]
Looks like they have updated to Python 3.7! I'll need to update the module to use the right conda installers. Thanks for the report!

**Comment by jaimergp** [comment]
@wfreinhart can you try again with these temporary instructions?

```python
!pip install -q https://github.com/jaimergp/condacolab/archive/py37.zip
import condacolab
condacolab.install()
```

The rest should be the same.

**Comment by wfreinhart** [comment]
It looks like this fix works for both your example notebook and my own.

**Comment by jaimergp** [comment]
Awesome! I'll cut a release then.

**Comment by jaimergp** [comment]
Available here: https://pypi.org/project/condacolab/0.1.2/

**Comment by cmspeed** [comment]
I came across this thread while troubleshooting a similar issue as above - this time with Pin: python=3.10. I am met with the following:

> Your pinning does not match what's currently installed. Please remove the pin and fix your installation
  Pin: python=3.10
  Currently installed: conda-forge/linux-64::python==3.9.16=h2782a2a_0_cpython

As a result, I am unable to mamba install the desired libraries in Colab. How might I be able to proceed? Should I use the `!pip install -q https://github.com/jaimergp/condacolab/archive/py37.zip` workaround as above temporarily?

Thanks for the help!

**Comment by mariabilichenk0** [comment]
> I came across this thread while troubleshooting a similar issue as above - this time with Pin: python=3.10. I am met with the following:
> 
> > Your pinning does not match what's currently installed. Please remove the pin and fix your installation
> > Pin: python=3.10
> > Currently installed: conda-forge/linux-64::python==3.9.16=h2782a2a_0_cpython
> 
> As a result, I am unable to mamba install the desired libraries in Colab. How might I be able to proceed? Should I use the `!pip install -q https://github.com/jaimergp/condacolab/archive/py37.zip` workaround as above temporarily?
> 
> Thanks for the help!

Having the same issue, would appreciate your help

**Comment by BelizSertcan** [comment]
> I came across this thread while troubleshooting a similar issue as above - this time with Pin: python=3.10. I am met with the following:
> 
> > Your pinning does not match what's currently installed. Please remove the pin and fix your installation
> > Pin: python=3.10
> > Currently installed: conda-forge/linux-64::python==3.9.16=h2782a2a_0_cpython
> 
> As a result, I am unable to mamba install the desired libraries in Colab. How might I be able to proceed? Should I use the `!pip install -q https://github.com/jaimergp/condacolab/archive/py37.zip` workaround as above temporarily?
> 
> Thanks for the help!

Same issue here 🤚

**Comment by jaimergp** [comment]
Did colab move to Python 3.10?

**Comment by jaimergp** [comment]
Yea looks like it:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/2559438/235132211-19d1b863-51d2-4555-bc48-444f81e926e8.png">


I'll update the infra.

**Comment by jaimergp** [comment]
Can you give `!pip install -q https://github.com/conda-incubator/condacolab/archive/py310.zip` a try?

**Comment by mariabilichenk0** [comment]
> Can you give `!pip install -q https://github.com/conda-incubator/condacolab/archive/py310.zip` a try?

It's working now 🥳 Thanks a lot!

**Comment by cmspeed** [comment]
> Can you give `!pip install -q https://github.com/conda-incubator/condacolab/archive/py310.zip` a try?

That works for me as well. Appreciate your quick work on this @jaimergp! I have several workflows built around using condacolab and mamba in Colab, so I may be in touch again in the future when they move the 3.11, etc. I can either open a new issue at that time or continue this thread.

Thanks again!

**Comment by jaimergp** [comment]
Yes, please, open a new issue when Colab updates to Python 3.11.

I'll cut a release now. Thanks for the reports!

**Comment by jaimergp** [comment]
0.1.7 now [available](https://pypi.org/project/condacolab/). Closing here!
