### ISSUE TITLE
Getting AssertionError while installing from URL

### ISSUE THREAD

**Issue by matcovic** [conda-incubator/condacolab#42]
![image](https://user-images.githubusercontent.com/49493045/201525402-f6f52a69-c408-400f-a5cc-9c5e5355385c.png)

**Here is the log file:**

```
__installer__.sh: line 1: syntax error near unexpected token `<'
__installer__.sh: line 1: `<!DOCTYPE html><html class="maestro global-header" lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><script nonce="veW741GqN7C2UONCw7GW">'
```

**Comment by jaimergp** [comment]
Sounds like the URL you are providing doesn't really return the installer itself, but a website (given the `<!DOCTYPE html>...` stuff).

Make sure your URL returns a valid `.sh` file (its contents should start with `#!`) by debugging locally with:

```
$ wget YOUR_URL
# or
$ curl -LO YOUR_URL
```

AFAIK, dropbox doesn't provide a true direct link.
