### ISSUE TITLE
Colab - Your pinning does not match what's currently installed. Please remove the pin and fix your installation   Pin: python=3.9

### ISSUE THREAD

**Issue by rayx1** [conda-incubator/condacolab#46]
Looking for: ['python=3.7', 'openmm']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Your pinning does not match what's currently installed. Please remove the pin and fix your installation
  Pin: python=3.9
  Currently installed: conda-forge/linux-64::python==3.8.15=h4a9ceb5_0_cpython

**Comment by jaimergp** [comment]
Hi, thanks for the report!

Can you try with this hotfix? If it works I'll cut a new 0.1.x release:

```python
!pip install -q https://github.com/conda-incubator/condacolab/archive/py39.tar.gz
import condacolab
condacolab.install()
```

**Comment by tonigi** [comment]
Works for me. So timely! Thanks!

**Comment by pablo-arantes** [comment]
It worked for me too. Thank you!

**Comment by jaimergp** [comment]
0.1.6 is now out!

- https://github.com/conda-incubator/condacolab/releases/tag/v0.1.6
- https://pypi.org/project/condacolab/
